ODP-7979: Add missing commons-collections dependency in agents-common to fix HBase Ranger coprocessor NoClassDefFoundError (#212)
* ODP-7979: Add missing commons-collections dependency in agents-common to fix HBase Ranger coprocessor NoClassDefFoundError

* ODP-7979: sort pom